spring.application.name=inventory-assistant
server.servlet.context-path=/ia

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true

springdoc.swagger-ui.path: /swagger-ui.html
springdoc.swagger-ui.tags-sorter: alpha
springdoc.swagger-ui.operations-sorter: alpha
springdoc.api-docs.path: /v3/api-docs

# application.properties
jwt.expiration=86400000

