spring.application.name=inventory-assistant
server.port=80
server.servlet.context-path=/ia

ssl.enabled=true
ssl.key-store: classpath:keystore.p12
ssl.key-store-password: 123qwe
ssl.key-store-type: PKCS12
ssl.key-alias: ia


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/inventory_assistant}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true

springdoc.swagger-ui.path: /swagger-ui.html
springdoc.swagger-ui.tags-sorter: alpha
springdoc.swagger-ui.operations-sorter: alpha
springdoc.api-docs.path: /v3/api-docs

# application.properties
jwt.secret=recoverSupermarketSecretKey2026!!
jwt.expiration=86400000

